### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by Sathishjekamus** [nazmulkp/NHAwesomeMovieApp#1]
I have downloaded your project using this link https://github.com/nazmulkp/NHAwesomeMovieApp. When I am trying to run the project, I got to know there some class files are missing. I could not select simulators also to run your project. PFA
<img width="1280" alt="dataManger" src="https://user-images.githubusercontent.com/56023957/65952113-02b5b680-e45f-11e9-9682-d30fdbcc7371.png">
<img width="768" alt="dataManager1" src="https://user-images.githubusercontent.com/56023957/65952158-14975980-e45f-11e9-96c5-7082a2d74dbc.png">
<img width="1280" alt="dataManger2" src="https://user-images.githubusercontent.com/56023957/65952177-1bbe6780-e45f-11e9-89d4-5acfea9c5095.png">

**Comment by Sathishjekamus** [comment]
I am using Xcode 10.1 and Swift 4.2

**Comment by nazmulkp** [comment]
I remove manager folder and now supporting from OS 10. where it was 12.2 that might be made a issue. hope it will work from Master branch but if not working with master branch than try with [swift4.2](https://github.com/nazmulkp/NHAwesomeMovieApp/tree/swift4.2) which are your machine swift version.

**Comment by Sathishjekamus** [comment]
Now it's working with swift 4.2. Very thanx

**Comment by nazmulkp** [comment]
issue fixed.

**Comment by Sathishjekamus** [comment]
Do you have any samples with unit testing and UI testing

**Comment by nazmulkp** [comment]
Please open another ticket. fork and star for future updated.

**Comment by Sathishjekamus** [comment]
Sure

Thanks and Regards,

*Sathishkumar Kalimuthan |*  *Head of Mobile*

sathishkalimuthan@gmail.com <sathishkumark@wilcosource.com> |
sathishkumark@pixelsandcodes.com | https://pixelsandcodes.com  | +91-99656
58042
No 2, Pixlsandcodes Consultancy Pvt Ltd, First Floor, Ayyapa nagar 1st
street, Duraisamy garden, Nanganallur, Chennai, Tamil Nadu 600061

**Comment by Sathishjekamus** [comment]
Hi,
 Opened a new ticket. Please have a look

Thanks and Regards,

*Sathishkumar Kalimuthan |*  *Head of Mobile*

sathishkalimuthan@gmail.com <sathishkumark@wilcosource.com> |
sathishkumark@pixelsandcodes.com | https://pixelsandcodes.com  | +91-99656
58042
No 2, Pixlsandcodes Consultancy Pvt Ltd, First Floor, Ayyapa nagar 1st
street, Duraisamy garden, Nanganallur, Chennai, Tamil Nadu 600061
